### ISSUE TITLE
Dockerize maple workflow

### ISSUE THREAD

**Issue by tcnichol** [PermafrostDiscoveryGateway/MAPLE_v3#13]
Create a Dockerfile and run maple workflow using that Docker image. Make sure that dependencies are handled correctly, paths set from environment variables, and path to data (input and output) mounted.

**Comment by tcnichol** [comment]
The Docker container now builds and has all required dependencies. However, I am getting an error:

```
arguments provided
Namespace(gpus_per_core=1, image='test_image_01.tif', root_dir='', weight_file='hyp_best_train_weights_final.h5')
1.start caculating wartermask
2. start tiling image
/data/divided_img/test_image_01
/data/input_img_local/test_image_01.tif
Traceback (most recent call last):
  File "maple_workflow.py", line 324, in <module>
    tile_image(config, image_name)
  File "maple_workflow.py", line 78, in tile_image
    divide.divide_image(config, input_img_path, crop_size, file1, file2)
  File "/mpl_divideimg_234_water_new.py", line 181, in divide_image
    dbfile = open(db_file_path, "wb")
FileNotFoundError: [Errno 2] No such file or directory: '/data/neighbors/test_image_01_ij_dict.pkl'
```

Could use some suggestions on what might be going wrong.

**Comment by tcnichol** [comment]
Above is fixed in another pull request.
